export const actionTypes = {

	BID_DETAIL_REQUEST: 'BID_DETAIL_REQUEST',
	BID_DETAIL_SUCCESS: 'BID_DETAIL_SUCCESS',
	BID_DETAIL_FAILURE: 'BID_DETAIL_FAILURE',

	ANTI_BOT_REQUEST: 'ANTI_BOT_REQUEST',
	ANTI_BOT_SUCCESS: 'ANTI_BOT_SUCCESS',
	ANTI_BOT_FAILURE: 'ANTI_BOT_FAILURE',
};