import { useState } from "react";
import { Modal, Button, Form } from "react-bootstrap";
import { decodeToken } from "react-jwt";
import { toast } from "react-toastify";

export default function ConfirmationModal({
  show,
  setShow,
  walletAddress,
  setVanityAddress,
  setIsIssuerKey,
  familySeed
}) {
  const token = localStorage.getItem("jwtToken");
  const ADDRESS = decodeToken(token);

  const [enabled, setEnabled] = useState(false);
  const [extra, setExtra] = useState("");

  const handleProcess = () => {
    const fullAddressRegex = /^r[1-9A-HJ-NP-Za-km-z]{33}$/;
    const extraTrimmed = extra.trim();

    if (!enabled && walletAddress !== ADDRESS.ac) {
      toast.error(
        "Wallet address should match with your generated seed's address ",
        {
          id: "confirmModalError" + Date.now()
        }
      );
      return;
    }

    // for vanity address if enabled
    if (enabled && extraTrimmed === "") {
      toast.error("Please enter vanity address", {
        id: "vanityError" + Date.now()
      });
      return;
    }

    if (enabled && !fullAddressRegex.test(extraTrimmed)) {
      toast.error("Vanity address is invalid (must be 34 chars & Base58).", {
        id: "fullAddressInvalid" + Date.now()
      });
      return;
    }
    alert("Success");
    setVanityAddress(extraTrimmed);
    setIsIssuerKey(familySeed);
    handleClose();
  };

  const handleClose = () => {
    setShow(false);
    setEnabled(false);
    setExtra("");
  };

  return (
    <div className="p-4">
      <Modal
        show={show}
        onHide={handleClose}
        dialogClassName="top-modal"
        backdropClassName="blur-backdrop"
      >
        <Modal.Header closeButton>
          <div className="text-center pt-2 word-break">
            <h5 className="responsive-address">{walletAddress}</h5>
          </div>
        </Modal.Header>

        <Modal.Body>
          {/* <p style={{ color: "#b00", fontWeight: 600 }}>
            Are you sure you want to process it?
          </p> */}
          <p style={{ fontSize: "12px" }}>
            If you have a Vanity Address attached to your Wallet Address and you
            wish to enable your Vanity Address as the permanent issuer for your
            NFTs. You will need to input the Vanity Address (Exactly) in the
            input field.
          </p>
          <p style={{ fontSize: "12px" }}>
            Be 100% sure your Vanity Address was generated by the wallet -
            family seed you have generated.
          </p>
          <p style={{ fontSize: "12px" }}>
            If you do not have a Vanity Address, simply click process.
          </p>

          <Form>
            <Form.Check
              type="switch"
              id="enable-switch"
              label="Vanity Address"
              checked={enabled}
              onChange={(e) => setEnabled(e.target.checked)}
            />

            {
              enabled && (
                <Form.Group className="mt-3">
                  <Form.Label>Add you Vanity Address</Form.Label>
                  <Form.Control
                    type="text"
                    value={extra}
                    onChange={(e) => setExtra(e.target.value)}
                    // isInvalid={validated && extra.trim() === ""}
                    placeholder="Type here..."
                  />
                  <Form.Control.Feedback type="invalid">
                    This field is required when enabled.
                  </Form.Control.Feedback>
                </Form.Group>
              )
              // : (
              //   <Form.Text muted>
              //     Toggle is off — no extra input required.
              //   </Form.Text>
              // )
            }
          </Form>
        </Modal.Body>

        <Modal.Footer>
          <Button variant="secondary" onClick={handleClose}>
            Cancel
          </Button>
          <Button variant="danger" onClick={handleProcess}>
            Process
          </Button>
        </Modal.Footer>
      </Modal>
    </div>
  );
}
